// Imports
  // imports GraphQL scalar types that we will use to specify the data types of our fields
import { GraphQLInt } from 'graphql'

// App Imports
  // imports the types defined in types.js; this us used to tell operations what kind of object w/ which fields to return in the HTTP response
import SubscriptionType from './types'
  // imports the resolver functions that should be executed when the query types below are called
import { create, remove } from './resolvers'

// Subscription create
  // defines the operation to be executed when the subscriptionCreate query is received; defines the arguments accepted by the query, the resolver function to execute, and the type of object to return
  // we will need to add an argument in order to accept the style information generated by the front-end when a user completes the style survey
export const subscriptionCreate = {
  type: SubscriptionType,
  args: {
    crateId: {
      name: 'crateId',
      type: GraphQLInt
    }
  },
  resolve: create
}

// Subscription remove
export const subscriptionRemove = {
  type: SubscriptionType,
  args: {
    id: {
      name: 'id',
      type: GraphQLInt
    }
  },
  resolve: remove
}
